// Word Bank for Password Game
// Each word has: id, category, word, banned (words that cannot be used as hints)

const CATEGORIES = {
  FOOTBALL: 'football',
  CRICKET: 'cricket',
  POLITICS: 'politics',
  GENZ: 'gen-z',
  INTERNET: 'internet',
  TECH: 'tech',
  POPCULTURE: 'popculture',
};

const WORDS = [
  // ─────────────────────────────── FOOTBALL ───────────────────────────────
  { id: 'f001', category: 'football', word: 'Offside', banned: ['line', 'position', 'flag', 'trap', 'defender', 'rule'] },
  { id: 'f002', category: 'football', word: 'Penalty', banned: ['kick', 'spot', 'foul', 'box', 'shoot', 'twelve'] },
  { id: 'f003', category: 'football', word: 'Hat-trick', banned: ['three', 'goals', 'score', 'same', 'consecutive', 'scoring'] },
  { id: 'f004', category: 'football', word: 'Goalkeeper', banned: ['save', 'keeper', 'goalie', 'hands', 'net', 'gloves'] },
  { id: 'f005', category: 'football', word: 'Corner kick', banned: ['flag', 'arc', 'cross', 'short', 'inswing', 'set'] },
  { id: 'f006', category: 'football', word: 'Yellow card', banned: ['booking', 'warning', 'caution', 'foul', 'referee', 'second'] },
  { id: 'f007', category: 'football', word: 'Red card', banned: ['dismissed', 'ejection', 'foul', 'serious', 'straight', 'off'] },
  { id: 'f008', category: 'football', word: 'Header', banned: ['head', 'ball', 'nod', 'aerial', 'forehead', 'goal'] },
  { id: 'f009', category: 'football', word: 'Free kick', banned: ['wall', 'direct', 'indirect', 'foul', 'dead', 'set'] },
  { id: 'f010', category: 'football', word: 'Dribble', banned: ['ball', 'feet', 'run', 'control', 'skill', 'move'] },
  { id: 'f011', category: 'football', word: 'Nutmeg', banned: ['legs', 'through', 'cheeky', 'trick', 'between', 'humiliate'] },
  { id: 'f012', category: 'football', word: 'Striker', banned: ['forward', 'goals', 'attack', 'center', 'scoring', 'nine'] },
  { id: 'f013', category: 'football', word: 'Assist', banned: ['pass', 'setup', 'last', 'final', 'goal', 'provide'] },
  { id: 'f014', category: 'football', word: 'Clean sheet', banned: ['zero', 'concede', 'shutout', 'defense', 'none', 'blank'] },
  { id: 'f015', category: 'football', word: 'Stoppage time', banned: ['injury', 'added', 'extra', 'end', 'minutes', 'fourth'] },
  { id: 'f016', category: 'football', word: 'Volley', banned: ['air', 'kick', 'half', 'shot', 'laces', 'bounce'] },
  { id: 'f017', category: 'football', word: 'Bicycle kick', banned: ['overhead', 'acrobatic', 'flip', 'back', 'aerial', 'spectacular'] },
  { id: 'f018', category: 'football', word: 'Diving', banned: ['fall', 'simulate', 'cheat', 'penalty', 'fake', 'con'] },
  { id: 'f019', category: 'football', word: 'Own goal', banned: ['accidentally', 'own', 'defender', 'net', 'embarrassing', 'mistake'] },
  { id: 'f020', category: 'football', word: 'Throw-in', banned: ['sideline', 'boundary', 'hands', 'restart', 'out', 'both'] },
  { id: 'f021', category: 'football', word: 'Substitute', banned: ['bench', 'replace', 'swap', 'off', 'come', 'change'] },
  { id: 'f022', category: 'football', word: 'Winger', banned: ['wide', 'flanks', 'speed', 'cross', 'outside', 'left'] },
  { id: 'f023', category: 'football', word: 'Midfielder', banned: ['center', 'control', 'linking', 'pass', 'zone', 'box'] },
  { id: 'f024', category: 'football', word: 'Counter-attack', banned: ['fast', 'break', 'transition', 'quick', 'speed', 'offense'] },
  { id: 'f025', category: 'football', word: 'VAR', banned: ['video', 'review', 'technology', 'check', 'decision', 'replay'] },
  { id: 'f026', category: 'football', word: 'Chip shot', banned: ['lob', 'lift', 'dink', 'over', 'goalkeeper', 'clever'] },
  { id: 'f027', category: 'football', word: 'Golden Boot', banned: ['top', 'scorer', 'award', 'goals', 'season', 'trophy'] },
  { id: 'f028', category: 'football', word: 'Brace', banned: ['two', 'double', 'goals', 'same', 'scored', 'pair'] },
  { id: 'f029', category: 'football', word: 'Formation', banned: ['tactics', 'shape', 'system', 'lineup', 'four', 'three'] },
  { id: 'f030', category: 'football', word: 'High press', banned: ['intensity', 'defend', 'hunt', 'pressure', 'klopp', 'forward'] },
  { id: 'f031', category: 'football', word: 'Penalty shootout', banned: ['spot', 'kicks', 'tiebreaker', 'pressure', 'goalkeeper', 'alternating'] },
  { id: 'f032', category: 'football', word: 'Extra time', banned: ['overtime', 'additional', 'thirty', 'minutes', 'tie', 'end'] },
  { id: 'f033', category: 'football', word: 'Backheel', banned: ['trick', 'behind', 'foot', 'clever', 'unexpected', 'flick'] },
  { id: 'f034', category: 'football', word: 'Derby', banned: ['local', 'rivals', 'city', 'same', 'fixture', 'rivalry'] },
  { id: 'f035', category: 'football', word: 'Relegation', banned: ['drop', 'down', 'division', 'league', 'bottom', 'fall'] },
  { id: 'f036', category: 'football', word: 'Promotion', banned: ['up', 'division', 'league', 'top', 'win', 'rise'] },
  { id: 'f037', category: 'football', word: 'Set piece', banned: ['dead', 'corner', 'free', 'penalty', 'rehearsed', 'training'] },
  { id: 'f038', category: 'football', word: 'Offside trap', banned: ['line', 'timing', 'defense', 'clever', 'catch', 'run'] },
  { id: 'f039', category: 'football', word: 'Sweeper keeper', banned: ['goalkeeper', 'defense', 'outside', 'box', 'Neuer', 'sweep'] },
  { id: 'f040', category: 'football', word: 'False nine', banned: ['striker', 'deep', 'drop', 'position', 'role', 'center'] },
  { id: 'f041', category: 'football', word: 'Pressing trap', banned: ['high', 'press', 'ball', 'force', 'error', 'pressure'] },
  { id: 'f042', category: 'football', word: 'Caretaker manager', banned: ['temporary', 'interim', 'sacked', 'until', 'replacement', 'fill'] },
  { id: 'f043', category: 'football', word: 'Transfer window', banned: ['buy', 'sell', 'sign', 'January', 'Summer', 'deal'] },
  { id: 'f044', category: 'football', word: 'Aggregate score', banned: ['two', 'legs', 'combined', 'total', 'tie', 'away'] },
  { id: 'f045', category: 'football', word: 'Away goals rule', banned: ['tiebreaker', 'away', 'score', 'tie', 'UEFA', 'abolished'] },

  // ─────────────────────────────── CRICKET ───────────────────────────────
  { id: 'c001', category: 'cricket', word: 'Wicket', banned: ['stumps', 'out', 'dismiss', 'fall', 'take', 'pitch'] },
  { id: 'c002', category: 'cricket', word: 'Bouncer', banned: ['short', 'pitch', 'head', 'fast', 'hostile', 'delivery'] },
  { id: 'c003', category: 'cricket', word: 'LBW', banned: ['leg', 'before', 'wicket', 'decision', 'pad', 'out'] },
  { id: 'c004', category: 'cricket', word: 'Googly', banned: ['spin', 'wrong', 'wrist', 'turn', 'leg', 'trick'] },
  { id: 'c005', category: 'cricket', word: 'Century', banned: ['hundred', 'runs', 'milestone', 'bat', 'score', 'hundred'] },
  { id: 'c006', category: 'cricket', word: 'Duck', banned: ['zero', 'runs', 'batsman', 'out', 'score', 'nought'] },
  { id: 'c007', category: 'cricket', word: 'Maiden over', banned: ['zero', 'runs', 'six', 'balls', 'bowler', 'over'] },
  { id: 'c008', category: 'cricket', word: 'Yorker', banned: ['feet', 'toe', 'delivery', 'stumps', 'fast', 'base'] },
  { id: 'c009', category: 'cricket', word: 'Doosra', banned: ['spin', 'opposite', 'turn', 'off', 'delivery', 'finger'] },
  { id: 'c010', category: 'cricket', word: 'Powerplay', banned: ['fielding', 'restriction', 'overs', 'circle', 'mandatory', 'attack'] },
  { id: 'c011', category: 'cricket', word: 'DRS', banned: ['review', 'system', 'technology', 'ball', 'hawk', 'decision'] },
  { id: 'c012', category: 'cricket', word: 'Tailender', banned: ['bottom', 'order', 'batsman', 'nine', 'ten', 'eleven'] },
  { id: 'c013', category: 'cricket', word: 'Cover drive', banned: ['shot', 'elegant', 'off', 'side', 'bat', 'timing'] },
  { id: 'c014', category: 'cricket', word: 'Reverse sweep', banned: ['shot', 'switch', 'unorthodox', 'bat', 'hand', 'flip'] },
  { id: 'c015', category: 'cricket', word: 'The Ashes', banned: ['England', 'Australia', 'urn', 'series', 'rivalry', 'Test'] },
  { id: 'c016', category: 'cricket', word: 'T20', banned: ['format', 'twenty', 'overs', 'short', 'IPL', 'blast'] },
  { id: 'c017', category: 'cricket', word: 'Follow-on', banned: ['deficit', 'bat', 'second', 'innings', 'enforce', 'behind'] },
  { id: 'c018', category: 'cricket', word: 'Hat-trick', banned: ['three', 'wickets', 'consecutive', 'balls', 'bowler', 'rare'] },
  { id: 'c019', category: 'cricket', word: 'Duckworth-Lewis', banned: ['rain', 'method', 'target', 'revised', 'weather', 'calculation'] },
  { id: 'c020', category: 'cricket', word: 'Slog sweep', banned: ['shot', 'swing', 'leg', 'side', 'aggressive', 'hit'] },
  { id: 'c021', category: 'cricket', word: 'Run out', banned: ['direct', 'hit', 'crease', 'throw', 'fielder', 'stumps'] },
  { id: 'c022', category: 'cricket', word: 'Stumped', banned: ['wicketkeeper', 'crease', 'out', 'missed', 'quick', 'gloves'] },
  { id: 'c023', category: 'cricket', word: 'Mankad', banned: ['non-striker', 'run', 'backing', 'bowler', 'dismissal', 'controversial'] },
  { id: 'c024', category: 'cricket', word: 'Beamer', banned: ['head', 'high', 'full', 'toss', 'dangerous', 'illegal'] },
  { id: 'c025', category: 'cricket', word: 'Swing bowling', banned: ['movement', 'air', 'seam', 'lateral', 'ball', 'deviation'] },
  { id: 'c026', category: 'cricket', word: 'Pull shot', banned: ['short', 'bounce', 'leg', 'side', 'hook', 'aggressive'] },
  { id: 'c027', category: 'cricket', word: 'Test match', banned: ['five', 'days', 'longest', 'format', 'whites', 'traditional'] },
  { id: 'c028', category: 'cricket', word: 'Super over', banned: ['tie', 'tiebreaker', 'one', 'additional', 'T20', 'final'] },
  { id: 'c029', category: 'cricket', word: 'Slip cordon', banned: ['fielder', 'behind', 'edge', 'catch', 'position', 'close'] },
  { id: 'c030', category: 'cricket', word: 'No ball', banned: ['front', 'foot', 'overstepping', 'crease', 'illegal', 'free'] },
  { id: 'c031', category: 'cricket', word: 'Wide ball', banned: ['outside', 'reach', 'batsman', 'extra', 'runs', 'illegal'] },
  { id: 'c032', category: 'cricket', word: 'Golden duck', banned: ['first', 'ball', 'zero', 'out', 'dismissed', 'debut'] },
  { id: 'c033', category: 'cricket', word: 'Batting average', banned: ['runs', 'innings', 'statistic', 'performance', 'divide', 'score'] },
  { id: 'c034', category: 'cricket', word: 'Economy rate', banned: ['bowler', 'runs', 'over', 'statistic', 'cost', 'concede'] },
  { id: 'c035', category: 'cricket', word: 'Nightwatchman', banned: ['lower', 'order', 'protect', 'end', 'day', 'batsman'] },
  { id: 'c036', category: 'cricket', word: 'Inswinger', banned: ['swing', 'into', 'batsman', 'late', 'seam', 'delivery'] },
  { id: 'c037', category: 'cricket', word: 'Outswinger', banned: ['swing', 'away', 'batsman', 'late', 'seam', 'edge'] },
  { id: 'c038', category: 'cricket', word: 'Caught behind', banned: ['edge', 'wicketkeeper', 'gloves', 'catch', 'snick', 'dismiss'] },
  { id: 'c039', category: 'cricket', word: 'Flick shot', banned: ['wrist', 'leg', 'side', 'elegant', 'bat', 'turn'] },
  { id: 'c040', category: 'cricket', word: 'Death overs', banned: ['final', 'last', 'power', 'hitting', 'slog', 'T20'] },

  // ─────────────────────────────── POLITICS ───────────────────────────────
  { id: 'p001', category: 'politics', word: 'Veto', banned: ['block', 'reject', 'president', 'power', 'stop', 'override'] },
  { id: 'p002', category: 'politics', word: 'Filibuster', banned: ['delay', 'speech', 'senate', 'talk', 'block', 'long'] },
  { id: 'p003', category: 'politics', word: 'Impeachment', banned: ['remove', 'charges', 'president', 'trial', 'congress', 'misconduct'] },
  { id: 'p004', category: 'politics', word: 'Gerrymandering', banned: ['district', 'redraw', 'map', 'boundary', 'favor', 'electoral'] },
  { id: 'p005', category: 'politics', word: 'Lobbying', banned: ['influence', 'congress', 'corporation', 'money', 'advocate', 'senator'] },
  { id: 'p006', category: 'politics', word: 'Manifesto', banned: ['document', 'party', 'promises', 'policy', 'election', 'platform'] },
  { id: 'p007', category: 'politics', word: 'Coalition', banned: ['alliance', 'parties', 'together', 'government', 'majority', 'combine'] },
  { id: 'p008', category: 'politics', word: 'Referendum', banned: ['vote', 'public', 'question', 'direct', 'Brexit', 'yes'] },
  { id: 'p009', category: 'politics', word: 'Sovereignty', banned: ['power', 'state', 'independence', 'authority', 'control', 'supreme'] },
  { id: 'p010', category: 'politics', word: 'Propaganda', banned: ['biased', 'information', 'influence', 'government', 'persuade', 'mislead'] },
  { id: 'p011', category: 'politics', word: 'Incumbent', banned: ['current', 'holder', 'office', 'reelection', 'advantage', 'position'] },
  { id: 'p012', category: 'politics', word: 'Bipartisan', banned: ['both', 'parties', 'together', 'cooperation', 'across', 'divide'] },
  { id: 'p013', category: 'politics', word: 'Lame duck', banned: ['president', 'outgoing', 'term', 'end', 'limited', 'power'] },
  { id: 'p014', category: 'politics', word: 'Whistleblower', banned: ['expose', 'secret', 'leak', 'government', 'report', 'wrong'] },
  { id: 'p015', category: 'politics', word: 'Quorum', banned: ['minimum', 'members', 'vote', 'meeting', 'required', 'present'] },
  { id: 'p016', category: 'politics', word: 'Amendment', banned: ['change', 'constitution', 'law', 'modify', 'add', 'clause'] },
  { id: 'p017', category: 'politics', word: 'Treaty', banned: ['agreement', 'countries', 'international', 'sign', 'peace', 'binding'] },
  { id: 'p018', category: 'politics', word: 'Embargo', banned: ['ban', 'trade', 'sanction', 'block', 'export', 'country'] },
  { id: 'p019', category: 'politics', word: 'Cabinet reshuffle', banned: ['minister', 'change', 'move', 'appointment', 'PM', 'government'] },
  { id: 'p020', category: 'politics', word: 'Abstain', banned: ['vote', 'neither', 'blank', 'refuse', 'sitting', 'pass'] },
  { id: 'p021', category: 'politics', word: 'Dissolution', banned: ['parliament', 'election', 'end', 'new', 'called', 'break'] },
  { id: 'p022', category: 'politics', word: 'Prorogue', banned: ['suspend', 'parliament', 'delay', 'Queen', 'Boris', 'break'] },
  { id: 'p023', category: 'politics', word: 'Defection', banned: ['leave', 'party', 'switch', 'cross', 'floor', 'join'] },
  { id: 'p024', category: 'politics', word: 'By-election', banned: ['single', 'seat', 'vacancy', 'mid-term', 'constituency', 'death'] },
  { id: 'p025', category: 'politics', word: 'Proportional representation', banned: ['seats', 'votes', 'fair', 'system', 'mirror', 'percentage'] },
  { id: 'p026', category: 'politics', word: 'First past the post', banned: ['winner', 'takes', 'most', 'votes', 'system', 'UK'] },
  { id: 'p027', category: 'politics', word: 'Sanctions', banned: ['punish', 'country', 'economy', 'ban', 'trade', 'restrict'] },
  { id: 'p028', category: 'politics', word: 'Motion of no confidence', banned: ['vote', 'remove', 'PM', 'government', 'fail', 'trust'] },
  { id: 'p029', category: 'politics', word: 'State of emergency', banned: ['crisis', 'declare', 'government', 'suspend', 'temporary', 'power'] },
  { id: 'p030', category: 'politics', word: 'Pork barrel', banned: ['spending', 'local', 'project', 'politician', 'district', 'vote'] },
  { id: 'p031', category: 'politics', word: 'Swing voter', banned: ['undecided', 'both', 'parties', 'persuade', 'middle', 'change'] },
  { id: 'p032', category: 'politics', word: 'Spin doctor', banned: ['PR', 'media', 'positive', 'narrative', 'journalist', 'communicate'] },
  { id: 'p033', category: 'politics', word: 'Think tank', banned: ['research', 'policy', 'organisation', 'ideas', 'group', 'influence'] },
  { id: 'p034', category: 'politics', word: 'Populism', banned: ['people', 'elite', 'anti', 'movement', 'voice', 'politician'] },
  { id: 'p035', category: 'politics', word: 'Caucus', banned: ['group', 'party', 'meeting', 'Iowa', 'vote', 'primary'] },
  { id: 'p036', category: 'politics', word: 'Electoral college', banned: ['vote', 'America', 'electors', 'president', 'indirect', 'system'] },
  { id: 'p037', category: 'politics', word: 'Parliamentary privilege', banned: ['speech', 'immunity', 'MP', 'protection', 'legal', 'parliament'] },
  { id: 'p038', category: 'politics', word: 'Austerity', banned: ['cuts', 'spending', 'government', 'reduce', 'economy', 'public'] },
  { id: 'p039', category: 'politics', word: 'Nationalisation', banned: ['government', 'own', 'private', 'industry', 'take', 'public'] },
  { id: 'p040', category: 'politics', word: 'Privatisation', banned: ['sell', 'government', 'private', 'company', 'public', 'sector'] },

  // ─────────────────────────────── GEN-Z ───────────────────────────────
  { id: 'g001', category: 'gen-z', word: 'Slay', banned: ['king', 'queen', 'amazing', 'awesome', 'fab', 'werk'] },
  { id: 'g002', category: 'gen-z', word: 'No cap', banned: ['lying', 'seriously', 'real', 'true', 'honest', 'facts'] },
  { id: 'g003', category: 'gen-z', word: 'Rizz', banned: ['charm', 'attract', 'charisma', 'confidence', 'smooth', 'game'] },
  { id: 'g004', category: 'gen-z', word: 'Delulu', banned: ['delusional', 'fantasy', 'unrealistic', 'obsessed', 'imagination', 'crush'] },
  { id: 'g005', category: 'gen-z', word: 'Bussin', banned: ['food', 'amazing', 'delicious', 'great', 'fire', 'hits'] },
  { id: 'g006', category: 'gen-z', word: 'It\'s giving', banned: ['vibes', 'feels', 'energy', 'reminds', 'looks', 'exudes'] },
  { id: 'g007', category: 'gen-z', word: 'Main character', banned: ['protagonist', 'story', 'center', 'narcissistic', 'life', 'attention'] },
  { id: 'g008', category: 'gen-z', word: 'NPC', banned: ['character', 'game', 'background', 'boring', 'response', 'programmed'] },
  { id: 'g009', category: 'gen-z', word: 'Living rent free', banned: ['mind', 'obsessed', 'thinking', 'head', 'cannot', 'forget'] },
  { id: 'g010', category: 'gen-z', word: 'Caught in 4K', banned: ['caught', 'evidence', 'video', 'proof', 'undeniable', 'camera'] },
  { id: 'g011', category: 'gen-z', word: 'The Ick', banned: ['disgust', 'attraction', 'turn', 'off', 'feeling', 'cringe'] },
  { id: 'g012', category: 'gen-z', word: 'Situationship', banned: ['relationship', 'neither', 'dating', 'ambiguous', 'undefined', 'label'] },
  { id: 'g013', category: 'gen-z', word: 'Talking stage', banned: ['early', 'dating', 'texting', 'flirting', 'before', 'relationship'] },
  { id: 'g014', category: 'gen-z', word: 'Girl dinner', banned: ['random', 'snacks', 'meal', 'lazy', 'food', 'bits'] },
  { id: 'g015', category: 'gen-z', word: 'Bed rotting', banned: ['stay', 'lazy', 'day', 'sleep', 'phone', 'nothing'] },
  { id: 'g016', category: 'gen-z', word: 'Villain era', banned: ['bad', 'done', 'caring', 'selfish', 'ruthless', 'phase'] },
  { id: 'g017', category: 'gen-z', word: 'Roman Empire', banned: ['men', 'think', 'randomly', 'obsess', 'history', 'meme'] },
  { id: 'g018', category: 'gen-z', word: 'Understood the assignment', banned: ['nailed', 'perfect', 'knew', 'exactly', 'right', 'task'] },
  { id: 'g019', category: 'gen-z', word: 'Vibe check', banned: ['energy', 'assess', 'feeling', 'pass', 'fail', 'test'] },
  { id: 'g020', category: 'gen-z', word: 'Based', banned: ['confident', 'opinion', 'unapologetic', 'real', 'chad', 'cool'] },
  { id: 'g021', category: 'gen-z', word: 'Ate and left no crumbs', banned: ['perfect', 'flawless', 'performance', 'nothing', 'remain', 'incredible'] },
  { id: 'g022', category: 'gen-z', word: 'Lowkey', banned: ['secretly', 'quietly', 'subtly', 'somewhat', 'kind', 'slightly'] },
  { id: 'g023', category: 'gen-z', word: 'Highkey', banned: ['openly', 'obviously', 'very', 'super', 'loudly', 'clearly'] },
  { id: 'g024', category: 'gen-z', word: 'Gatekeep', banned: ['hide', 'secret', 'share', 'keep', 'tell', 'exclusive'] },
  { id: 'g025', category: 'gen-z', word: 'Serve', banned: ['look', 'outfit', 'model', 'fashion', 'stunning', 'bring'] },
  { id: 'g026', category: 'gen-z', word: 'Spill the tea', banned: ['gossip', 'drama', 'tell', 'secret', 'info', 'reveal'] },
  { id: 'g027', category: 'gen-z', word: 'CEO of', banned: ['best', 'known', 'representative', 'queen', 'king', 'master'] },
  { id: 'g028', category: 'gen-z', word: 'Very demure', banned: ['modest', 'quiet', 'mindful', 'subtle', 'calm', 'reserved'] },
  { id: 'g029', category: 'gen-z', word: 'Glow up', banned: ['transformation', 'better', 'improve', 'looks', 'upgrade', 'change'] },
  { id: 'g030', category: 'gen-z', word: 'Era', banned: ['phase', 'period', 'time', 'Taylor', 'life', 'stage'] },
  { id: 'g031', category: 'gen-z', word: 'Touch grass', banned: ['outside', 'nature', 'screen', 'real', 'life', 'offline'] },
  { id: 'g032', category: 'gen-z', word: 'Hits different', banned: ['feeling', 'special', 'unique', 'meaning', 'context', 'resonates'] },
  { id: 'g033', category: 'gen-z', word: 'That\'s sus', banned: ['suspicious', 'weird', 'sketchy', 'doubt', 'trust', 'Among'] },
  { id: 'g034', category: 'gen-z', word: 'Mother', banned: ['idol', 'icon', 'queen', 'worship', 'reverence', 'ultimate'] },
  { id: 'g035', category: 'gen-z', word: 'Brat', banned: ['Charli', 'green', 'album', 'attitude', 'messy', 'unapologetic'] },
  { id: 'g036', category: 'gen-z', word: 'Gyat', banned: ['reaction', 'surprise', 'body', 'exclamation', 'wow', 'curves'] },
  { id: 'g037', category: 'gen-z', word: 'Rizz W', banned: ['win', 'charmed', 'success', 'smooth', 'attract', 'score'] },
  { id: 'g038', category: 'gen-z', word: 'Rent free', banned: ['mind', 'thinking', 'cannot', 'stop', 'obsessed', 'head'] },
  { id: 'g039', category: 'gen-z', word: 'That slaps', banned: ['music', 'song', 'fire', 'amazing', 'beat', 'track'] },
  { id: 'g040', category: 'gen-z', word: 'Ghosting', banned: ['ignore', 'disappear', 'messages', 'stop', 'respond', 'vanish'] },

  // ─────────────────────────────── INTERNET SLANG ───────────────────────────────
  { id: 'i001', category: 'internet', word: 'Doomscrolling', banned: ['scroll', 'news', 'endless', 'depressing', 'phone', 'feed'] },
  { id: 'i002', category: 'internet', word: 'Catfish', banned: ['fake', 'identity', 'online', 'pretend', 'dating', 'profile'] },
  { id: 'i003', category: 'internet', word: 'Simp', banned: ['obsessed', 'crush', 'attention', 'pathetic', 'over', 'desperate'] },
  { id: 'i004', category: 'internet', word: 'FOMO', banned: ['fear', 'missing', 'out', 'party', 'anxiety', 'exclude'] },
  { id: 'i005', category: 'internet', word: 'Ratio', banned: ['replies', 'likes', 'ratio', 'comment', 'more', 'dunked'] },
  { id: 'i006', category: 'internet', word: 'Copypasta', banned: ['text', 'copy', 'paste', 'meme', 'repeat', 'viral'] },
  { id: 'i007', category: 'internet', word: 'Shitpost', banned: ['irrelevant', 'random', 'nonsense', 'post', 'troll', 'meme'] },
  { id: 'i008', category: 'internet', word: 'Shadowban', banned: ['invisible', 'hidden', 'platform', 'restrict', 'silent', 'account'] },
  { id: 'i009', category: 'internet', word: 'Clickbait', banned: ['headline', 'misleading', 'click', 'title', 'trick', 'sensational'] },
  { id: 'i010', category: 'internet', word: 'Parasocial', banned: ['one-sided', 'relationship', 'celebrity', 'feel', 'know', 'connection'] },
  { id: 'i011', category: 'internet', word: 'Cancel culture', banned: ['boycott', 'public', 'shaming', 'accountability', 'consequence', 'mob'] },
  { id: 'i012', category: 'internet', word: 'Thread', banned: ['tweet', 'series', 'connected', 'long', 'post', 'continuation'] },
  { id: 'i013', category: 'internet', word: 'Lurker', banned: ['read', 'never', 'post', 'observer', 'silent', 'watch'] },
  { id: 'i014', category: 'internet', word: 'Troll', banned: ['provocateur', 'online', 'bait', 'argument', 'negative', 'attention'] },
  { id: 'i015', category: 'internet', word: 'Meme', banned: ['image', 'funny', 'viral', 'culture', 'template', 'reference'] },
  { id: 'i016', category: 'internet', word: 'Phishing', banned: ['scam', 'email', 'fake', 'password', 'steal', 'link'] },
  { id: 'i017', category: 'internet', word: 'Spam', banned: ['unwanted', 'email', 'bulk', 'junk', 'filter', 'inbox'] },
  { id: 'i018', category: 'internet', word: 'Verified badge', banned: ['blue', 'tick', 'official', 'account', 'authentic', 'real'] },
  { id: 'i019', category: 'internet', word: 'DM slide', banned: ['direct', 'message', 'secretly', 'flirt', 'inbox', 'private'] },
  { id: 'i020', category: 'internet', word: 'Subtweet', banned: ['about', 'indirect', 'without', 'naming', 'passive', 'aggressive'] },
  { id: 'i021', category: 'internet', word: 'Finsta', banned: ['fake', 'second', 'private', 'Instagram', 'account', 'real'] },
  { id: 'i022', category: 'internet', word: 'Thirst trap', banned: ['sexy', 'photo', 'attention', 'attract', 'post', 'reaction'] },
  { id: 'i023', category: 'internet', word: 'AFK', banned: ['away', 'keyboard', 'offline', 'gone', 'not', 'here'] },
  { id: 'i024', category: 'internet', word: 'Doxxing', banned: ['expose', 'personal', 'information', 'address', 'private', 'reveal'] },
  { id: 'i025', category: 'internet', word: 'Clout chasing', banned: ['fame', 'viral', 'attention', 'popular', 'seeking', 'social'] },
  { id: 'i026', category: 'internet', word: 'Rabbit hole', banned: ['deep', 'dive', 'distraction', 'YouTube', 'endless', 'topic'] },
  { id: 'i027', category: 'internet', word: 'Main character syndrome', banned: ['narcissist', 'self-centered', 'world', 'revolves', 'around', 'protagonist'] },
  { id: 'i028', category: 'internet', word: 'Keyboard warrior', banned: ['brave', 'online', 'hide', 'screen', 'aggressive', 'coward'] },
  { id: 'i029', category: 'internet', word: 'Cringe', banned: ['embarrassing', 'awkward', 'secondhand', 'uncomfortable', 'reaction', 'watching'] },
  { id: 'i030', category: 'internet', word: 'IRL', banned: ['real', 'life', 'offline', 'actual', 'physical', 'world'] },
  { id: 'i031', category: 'internet', word: 'TL;DR', banned: ['summary', 'short', 'long', 'didn\'t', 'read', 'brief'] },
  { id: 'i032', category: 'internet', word: 'Touch grass', banned: ['outside', 'nature', 'offline', 'screen', 'real', 'life'] },
  { id: 'i033', category: 'internet', word: 'Based', banned: ['opinion', 'confident', 'based', 'real', 'true', 'unfiltered'] },
  { id: 'i034', category: 'internet', word: 'Clapback', banned: ['reply', 'comeback', 'witty', 'response', 'criticism', 'shut'] },
  { id: 'i035', category: 'internet', word: 'Going viral', banned: ['spread', 'share', 'millions', 'internet', 'trend', 'famous'] },
  { id: 'i036', category: 'internet', word: 'Normie', banned: ['ordinary', 'mainstream', 'boring', 'regular', 'not', 'internet'] },
  { id: 'i037', category: 'internet', word: 'Ship', banned: ['relationship', 'couple', 'want', 'together', 'fandom', 'pairing'] },
  { id: 'i038', category: 'internet', word: 'OTP', banned: ['one', 'true', 'pairing', 'favorite', 'couple', 'ship'] },
  { id: 'i039', category: 'internet', word: 'GOAT', banned: ['greatest', 'all', 'time', 'best', 'ever', 'supreme'] },
  { id: 'i040', category: 'internet', word: 'Power move', banned: ['dominant', 'flex', 'impressive', 'strategic', 'confident', 'action'] },

  // ─────────────────────────────── TECH ───────────────────────────────
  { id: 't001', category: 'tech', word: 'Algorithm', banned: ['step', 'instructions', 'computer', 'solve', 'process', 'code'] },
  { id: 't002', category: 'tech', word: 'Blockchain', banned: ['decentralized', 'crypto', 'chain', 'ledger', 'immutable', 'Bitcoin'] },
  { id: 't003', category: 'tech', word: 'Debugging', banned: ['bug', 'fix', 'error', 'code', 'find', 'problem'] },
  { id: 't004', category: 'tech', word: 'API', banned: ['interface', 'connect', 'services', 'endpoint', 'data', 'request'] },
  { id: 't005', category: 'tech', word: 'Cloud computing', banned: ['server', 'internet', 'storage', 'remote', 'host', 'AWS'] },
  { id: 't006', category: 'tech', word: 'Machine learning', banned: ['AI', 'data', 'train', 'model', 'pattern', 'neural'] },
  { id: 't007', category: 'tech', word: 'Recursion', banned: ['function', 'calls', 'itself', 'repeat', 'nested', 'loop'] },
  { id: 't008', category: 'tech', word: 'Firewall', banned: ['protect', 'network', 'block', 'security', 'filter', 'traffic'] },
  { id: 't009', category: 'tech', word: 'VPN', banned: ['private', 'network', 'encrypt', 'location', 'hide', 'tunnel'] },
  { id: 't010', category: 'tech', word: 'Cryptocurrency', banned: ['digital', 'Bitcoin', 'blockchain', 'wallet', 'mine', 'coin'] },
  { id: 't011', category: 'tech', word: 'NFT', banned: ['token', 'digital', 'unique', 'blockchain', 'art', 'ownership'] },
  { id: 't012', category: 'tech', word: 'Metaverse', banned: ['virtual', 'reality', 'Meta', 'world', '3D', 'online'] },
  { id: 't013', category: 'tech', word: 'Agile', banned: ['sprint', 'scrum', 'iterative', 'development', 'flexible', 'team'] },
  { id: 't014', category: 'tech', word: 'Tech debt', banned: ['code', 'quick', 'fix', 'later', 'future', 'shortcut'] },
  { id: 't015', category: 'tech', word: 'CAPTCHA', banned: ['human', 'bot', 'verify', 'test', 'robot', 'puzzle'] },
  { id: 't016', category: 'tech', word: 'Cache', banned: ['store', 'temporary', 'fast', 'memory', 'save', 'retrieve'] },
  { id: 't017', category: 'tech', word: 'Open source', banned: ['free', 'code', 'public', 'community', 'contribute', 'GitHub'] },
  { id: 't018', category: 'tech', word: 'Pull request', banned: ['merge', 'code', 'review', 'branch', 'GitHub', 'change'] },
  { id: 't019', category: 'tech', word: 'Full stack', banned: ['frontend', 'backend', 'both', 'developer', 'complete', 'all'] },
  { id: 't020', category: 'tech', word: 'Dark mode', banned: ['theme', 'black', 'white', 'switch', 'screen', 'eyes'] },
  { id: 't021', category: 'tech', word: 'Neural network', banned: ['brain', 'AI', 'layers', 'neurons', 'connections', 'machine'] },
  { id: 't022', category: 'tech', word: 'Bandwidth', banned: ['speed', 'internet', 'data', 'transfer', 'capacity', 'rate'] },
  { id: 't023', category: 'tech', word: 'Latency', banned: ['delay', 'lag', 'ping', 'response', 'time', 'slow'] },
  { id: 't024', category: 'tech', word: 'Rubber duck debugging', banned: ['talk', 'explain', 'code', 'inanimate', 'object', 'bug'] },
  { id: 't025', category: 'tech', word: 'MVP', banned: ['minimum', 'viable', 'product', 'startup', 'basic', 'launch'] },
  { id: 't026', category: 'tech', word: 'Scrum', banned: ['agile', 'sprint', 'standup', 'team', 'methodology', 'daily'] },
  { id: 't027', category: 'tech', word: 'Stack Overflow', banned: ['answer', 'developer', 'question', 'code', 'forum', 'copy'] },
  { id: 't028', category: 'tech', word: 'Git', banned: ['version', 'control', 'repository', 'commit', 'branch', 'code'] },
  { id: 't029', category: 'tech', word: 'Deployment', banned: ['release', 'production', 'server', 'live', 'publish', 'launch'] },
  { id: 't030', category: 'tech', word: 'Framework', banned: ['structure', 'React', 'template', 'code', 'build', 'library'] },
  { id: 't031', category: 'tech', word: 'Internet of Things', banned: ['connected', 'smart', 'devices', 'sensors', 'home', 'physical'] },
  { id: 't032', category: 'tech', word: 'Pixel', banned: ['screen', 'tiny', 'dot', 'resolution', 'image', 'display'] },
  { id: 't033', category: 'tech', word: 'Encryption', banned: ['scramble', 'secure', 'decode', 'key', 'private', 'protect'] },
  { id: 't034', category: 'tech', word: 'Phishing', banned: ['scam', 'email', 'fake', 'steal', 'link', 'credential'] },
  { id: 't035', category: 'tech', word: 'Two-factor authentication', banned: ['security', 'code', 'phone', 'verify', 'extra', 'login'] },
  { id: 't036', category: 'tech', word: 'Serverless', banned: ['cloud', 'function', 'AWS', 'Lambda', 'backend', 'host'] },
  { id: 't037', category: 'tech', word: 'DevOps', banned: ['development', 'operations', 'pipeline', 'CI', 'CD', 'automation'] },
  { id: 't038', category: 'tech', word: 'Zero-day exploit', banned: ['vulnerability', 'unknown', 'attack', 'patch', 'security', 'flaw'] },
  { id: 't039', category: 'tech', word: 'Prompt engineering', banned: ['AI', 'ChatGPT', 'instruct', 'optimize', 'language', 'model'] },
  { id: 't040', category: 'tech', word: 'Hallucination', banned: ['AI', 'false', 'wrong', 'confident', 'invent', 'mistake'] },

  // ─────────────────────────────── POP CULTURE ───────────────────────────────
  { id: 'pc001', category: 'popculture', word: 'TikTok', banned: ['short', 'video', 'app', 'China', 'ByteDance', 'For You'] },
  { id: 'pc002', category: 'popculture', word: 'Streaming', banned: ['Netflix', 'watch', 'online', 'binge', 'subscription', 'service'] },
  { id: 'pc003', category: 'popculture', word: 'Swifties', banned: ['Taylor', 'fans', 'dedicated', 'concert', 'Eras', 'fanbase'] },
  { id: 'pc004', category: 'popculture', word: 'K-pop', banned: ['Korean', 'music', 'idol', 'BTS', 'BLACKPINK', 'group'] },
  { id: 'pc005', category: 'popculture', word: 'Eras Tour', banned: ['Taylor', 'concert', 'tour', 'Swift', 'sold', 'out'] },
  { id: 'pc006', category: 'popculture', word: 'Marvel Cinematic Universe', banned: ['superhero', 'movies', 'Avengers', 'Iron Man', 'connected', 'universe'] },
  { id: 'pc007', category: 'popculture', word: 'Wordle', banned: ['five', 'letters', 'word', 'puzzle', 'New York', 'daily'] },
  { id: 'pc008', category: 'popculture', word: 'Spotify Wrapped', banned: ['year', 'listening', 'top', 'artist', 'annual', 'stats'] },
  { id: 'pc009', category: 'popculture', word: 'Barbie movie', banned: ['pink', 'Margot', 'Robbie', 'Greta', 'Gerwig', 'doll'] },
  { id: 'pc010', category: 'popculture', word: 'ChatGPT', banned: ['AI', 'OpenAI', 'chatbot', 'language', 'model', 'responses'] },
  { id: 'pc011', category: 'popculture', word: 'Binge-watching', banned: ['episodes', 'hours', 'series', 'consecutive', 'Netflix', 'marathon'] },
  { id: 'pc012', category: 'popculture', word: 'Podcast', banned: ['audio', 'episode', 'host', 'listen', 'show', 'interview'] },
  { id: 'pc013', category: 'popculture', word: 'Stan', banned: ['obsessed', 'fan', 'extreme', 'Eminem', 'follow', 'dedicated'] },
  { id: 'pc014', category: 'popculture', word: 'Cosplay', banned: ['costume', 'character', 'dress', 'convention', 'anime', 'fan'] },
  { id: 'pc015', category: 'popculture', word: 'Anime', banned: ['Japanese', 'cartoon', 'manga', 'subtitles', 'series', 'animation'] },
  { id: 'pc016', category: 'popculture', word: 'Isekai', banned: ['transported', 'another', 'world', 'genre', 'anime', 'reincarnate'] },
  { id: 'pc017', category: 'popculture', word: 'Sabrina Carpenter', banned: ['pop', 'singer', 'Espresso', 'Short n Sweet', 'blonde', 'tour'] },
  { id: 'pc018', category: 'popculture', word: 'Euphoria', banned: ['HBO', 'teen', 'drama', 'Zendaya', 'Rue', 'drugs'] },
  { id: 'pc019', category: 'popculture', word: 'Squid Game', banned: ['Netflix', 'Korean', 'survival', 'games', 'debt', 'prize'] },
  { id: 'pc020', category: 'popculture', word: 'Stranger Things', banned: ['Netflix', 'Upside', 'Down', 'Eleven', 'Hawkins', '80s'] },
  { id: 'pc021', category: 'popculture', word: 'Dua Lipa', banned: ['singer', 'Levitating', 'pop', 'dancefloor', 'British', 'Albanian'] },
  { id: 'pc022', category: 'popculture', word: 'Bad Bunny', banned: ['reggaeton', 'Puerto', 'Rican', 'Spanish', 'trap', 'rapper'] },
  { id: 'pc023', category: 'popculture', word: 'Beyoncé', banned: ['singer', 'Halo', 'Destiny\'s Child', 'Lemonade', 'Jay-Z', 'queen'] },
  { id: 'pc024', category: 'popculture', word: 'Succession', banned: ['HBO', 'Roy', 'family', 'media', 'empire', 'Logan'] },
  { id: 'pc025', category: 'popculture', word: 'The Bear', banned: ['FX', 'chef', 'restaurant', 'Chicago', 'kitchen', 'pressure'] },
  { id: 'pc026', category: 'popculture', word: 'White Lotus', banned: ['HBO', 'resort', 'wealthy', 'guests', 'Mike White', 'murder'] },
  { id: 'pc027', category: 'popculture', word: 'Wednesday Addams', banned: ['gothic', 'Addams', 'Family', 'Jenna', 'Ortega', 'dark'] },
  { id: 'pc028', category: 'popculture', word: 'Olivia Rodrigo', banned: ['SOUR', 'Drivers License', 'Disney', 'pop', 'heartbreak', 'singer'] },
  { id: 'pc029', category: 'popculture', word: 'Harry Styles', banned: ['pop', 'singer', 'One Direction', 'Watermelon Sugar', 'Harry\'s House', 'fashion'] },
  { id: 'pc030', category: 'popculture', word: 'Kendrick Lamar', banned: ['rapper', 'Pulitzer', 'Compton', 'Drake', 'Not Like Us', 'Super Bowl'] },
  { id: 'pc031', category: 'popculture', word: 'Zendaya', banned: ['actress', 'Euphoria', 'Rue', 'Spiderman', 'MJ', 'Dune'] },
  { id: 'pc032', category: 'popculture', word: 'Billie Eilish', banned: ['pop', 'singer', 'Bad Guy', 'Bond', 'green hair', 'whisper'] },
  { id: 'pc033', category: 'popculture', word: 'BTS', banned: ['Korean', 'boyband', 'Army', 'kpop', 'Bangtan', 'Jin'] },
  { id: 'pc034', category: 'popculture', word: 'BLACKPINK', banned: ['Korean', 'girlgroup', 'Lisa', 'Jennie', 'kpop', 'YG'] },
  { id: 'pc035', category: 'popculture', word: 'Roblox', banned: ['game', 'kids', 'virtual', 'world', 'Robux', 'create'] },
  { id: 'pc036', category: 'popculture', word: 'Game of Thrones', banned: ['HBO', 'dragons', 'Westeros', 'throne', 'war', 'fantasy'] },
  { id: 'pc037', category: 'popculture', word: 'Avatar', banned: ['blue', 'Pandora', 'Cameron', 'Na\'vi', 'sequel', 'movie'] },
  { id: 'pc038', category: 'popculture', word: 'Oppenheimer', banned: ['atomic', 'bomb', 'nuclear', 'Manhattan', 'Nolan', 'Cillian'] },
  { id: 'pc039', category: 'popculture', word: 'Taylor Swift', banned: ['singer', 'Eras', 'Tour', 'albums', 'country', 'pop'] },
  { id: 'pc040', category: 'popculture', word: 'Drake', banned: ['rapper', 'Canadian', 'Toronto', 'Hotline Bling', 'Views', 'OVO'] },
  { id: 'pc041', category: 'popculture', word: 'Ariana Grande', banned: ['pop', 'singer', 'Thank U Next', 'Manchester', 'ponytail', '7 rings'] },
  { id: 'pc042', category: 'popculture', word: 'The Weeknd', banned: ['Abel', 'Blinding Lights', 'Super Bowl', 'RnB', 'dark', 'singer'] },
  { id: 'pc043', category: 'popculture', word: 'Lil Uzi Vert', banned: ['rapper', 'XO Tour', 'face', 'diamond', 'rock', 'emo'] },
  { id: 'pc044', category: 'popculture', word: 'Pedro Pascal', banned: ['actor', 'Mandalorian', 'Joel', 'Last of Us', 'Chilean', 'daddy'] },
  { id: 'pc045', category: 'popculture', word: 'Saltburn', banned: ['Barry', 'Keoghan', 'Rosamund Pike', 'bathtub', 'stalker', 'movie'] },
];

// Get words by category filter
function getWords(categories = null) {
  if (!categories || categories.length === 0) return WORDS;
  return WORDS.filter(w => categories.includes(w.category));
}

// Get a random word excluding recently used
function getNextWord(usedIds = [], categories = null) {
  const pool = getWords(categories);
  const available = pool.filter(w => !usedIds.includes(w.id));

  // If too few available, reset (allow reuse of older words)
  const target = available.length > 0 ? available : pool;
  return target[Math.floor(Math.random() * target.length)];
}

module.exports = { WORDS, CATEGORIES, getWords, getNextWord };
